- name: Install Docker Engine on Ubuntu (official repo)
  hosts: swarm
  become: true
  tasks:
    - name: Base packages
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - python3-pip
        update_cache: true

    # (opcjonalnie) usuń konflikty, jeśli hosty miały docker.io itd.
    - name: Remove conflicting packages (optional but safe)
      ansible.builtin.apt:
        name:
          - docker.io
          - docker-compose
          - docker-compose-v2
          - docker-doc
          - podman-docker
          - containerd
          - runc
        state: absent
      ignore_errors: true

    - name: Create keyrings dir
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"

    - name: Add Docker GPG key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: "0644"

    - name: Add Docker apt repository
      ansible.builtin.apt_repository:
        repo: >-
          deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.asc]
          https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} {{ docker_apt_channel }}
        state: present
        filename: docker

    - name: Install Docker packages
      ansible.builtin.apt:
        name: "{{ docker_packages }}"
        update_cache: true

    - name: Enable and start docker
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    # wymagane dla community.docker.* (docker_swarm, docker_stack itd.)
    - name: Install Docker SDK for Python (for Ansible modules)
      ansible.builtin.pip:
        name: docker
