- name: Deploy a test service to Swarm
  hosts: swarm_managers[0]
  become: true
  collections:
    - community.docker

  tasks:
    - name: Create overlay network
      community.docker.docker_network:
        name: test-net
        driver: overlay
        scope: swarm

    - name: Deploy nginx service
      community.docker.docker_swarm_service:
        name: nginx-test
        image: nginx:alpine
        networks:
          - name: test-net
        publish:
          - published_port: 8080
            target_port: 80
        replicas: 2
        state: present
